DEMO_DATA = {
    "default_job": "java-backend-intern",
    "jobs": [
        {
            "id": "java-backend-intern",
            "title": "Java Backend Intern",
            "team": "Platform Engineering",
            "location": "Boston / Hybrid",
            "type": "Internship",
            "status": "Open",
            "requirements": ["Java", "Spring Boot", "SQL", "REST APIs"],
        },
        {
            "id": "data-engineering-intern",
            "title": "Data Engineering Intern",
            "team": "Data Platform",
            "location": "Remote - US",
            "type": "Internship",
            "status": "Open",
            "requirements": ["Python", "SQL", "dbt", "Data modeling"],
        },
    ],
    "candidates": [
        {
            "id": "sample-1042",
            "name": "Maya Chen",
            "initials": "MC",
            "headline": "Computer Science | Northeastern University",
            "location": "Boston, MA",
            "location_group": "Boston",
            "availability": "Available June 2026",
            "evidence": [
                {
                    "skill": "Java",
                    "kind": "Assessment",
                    "title": "Java fundamentals",
                    "verification": "Verified",
                    "detail": "88% assessment result",
                    "observed": "12 days ago",
                },
                {
                    "skill": "Spring Boot",
                    "kind": "Project",
                    "title": "Inventory API",
                    "verification": "Project evidence",
                    "detail": "Repository linked",
                    "observed": "6 weeks ago",
                },
                {
                    "skill": "SQL",
                    "kind": "Project",
                    "title": "Inventory API",
                    "verification": "Project evidence",
                    "detail": "Schema and query examples",
                    "observed": "6 weeks ago",
                },
                {
                    "skill": "Python",
                    "kind": "Project",
                    "title": "Course planner",
                    "verification": "Project evidence",
                    "detail": "Repository linked",
                    "observed": "3 months ago",
                },
            ],
        },
        {
            "id": "sample-1088",
            "name": "Ravi Patel",
            "initials": "RP",
            "headline": "Software Engineering | Rutgers University",
            "location": "New York, NY",
            "location_group": "New York",
            "availability": "Available May 2026",
            "evidence": [
                {
                    "skill": "Java",
                    "kind": "Project",
                    "title": "Transit tracker",
                    "verification": "Project evidence",
                    "detail": "Repository linked",
                    "observed": "3 weeks ago",
                },
                {
                    "skill": "SQL",
                    "kind": "Assessment",
                    "title": "SQL fundamentals",
                    "verification": "Verified",
                    "detail": "81% assessment result",
                    "observed": "9 days ago",
                },
                {
                    "skill": "REST APIs",
                    "kind": "Project",
                    "title": "Transit tracker",
                    "verification": "Project evidence",
                    "detail": "Documented API endpoints",
                    "observed": "3 weeks ago",
                },
                {
                    "skill": "Python",
                    "kind": "Assessment",
                    "title": "Python fundamentals",
                    "verification": "Verified",
                    "detail": "84% assessment result",
                    "observed": "1 month ago",
                },
            ],
        },
        {
            "id": "sample-1116",
            "name": "Lena Ortiz",
            "initials": "LO",
            "headline": "Computer Engineering | WPI",
            "location": "Worcester, MA",
            "location_group": "Boston",
            "availability": "Available July 2026",
            "evidence": [
                {
                    "skill": "Python",
                    "kind": "Assessment",
                    "title": "Python fundamentals",
                    "verification": "Verified",
                    "detail": "91% assessment result",
                    "observed": "5 days ago",
                },
                {
                    "skill": "SQL",
                    "kind": "Project",
                    "title": "Research data pipeline",
                    "verification": "Project evidence",
                    "detail": "Repository linked",
                    "observed": "2 weeks ago",
                },
                {
                    "skill": "Data modeling",
                    "kind": "Project",
                    "title": "Research data pipeline",
                    "verification": "Project evidence",
                    "detail": "Schema documentation",
                    "observed": "2 weeks ago",
                },
                {
                    "skill": "dbt",
                    "kind": "Assessment",
                    "title": "Analytics engineering",
                    "verification": "Verified",
                    "detail": "76% assessment result",
                    "observed": "3 weeks ago",
                },
            ],
        },
    ],
    "student": {
        "name": "Maya Chen",
        "program": "Computer Science | Northeastern University",
        "metrics": [
            {"label": "Evidence items", "value": "04", "note": "Across 4 skills"},
            {"label": "Active applications", "value": "02", "note": "One assessment in progress"},
            {"label": "Profile visibility", "value": "Opted in", "note": "Visible to verified recruiters"},
        ],
        "evidence": [
            {"title": "Java fundamentals", "skill": "Java", "kind": "Assessment", "status": "Verified", "date": "Sep 14, 2026"},
            {"title": "Inventory API", "skill": "Spring Boot and SQL", "kind": "Project", "status": "Project evidence", "date": "Aug 12, 2026"},
            {"title": "Course planner", "skill": "Python", "kind": "Project", "status": "Project evidence", "date": "Jul 30, 2026"},
        ],
        "skills": [
            {"name": "Java", "count": "1 item", "latest": "Assessment | Sep 14"},
            {"name": "Spring Boot", "count": "1 item", "latest": "Inventory API | Aug 12"},
            {"name": "SQL", "count": "1 item", "latest": "Inventory API | Aug 12"},
            {"name": "Python", "count": "1 item", "latest": "Course planner | Jul 30"},
        ],
        "applications": [
            {"role": "Backend Intern", "organization": "Meridian Works", "stage": "Assessment", "updated": "Updated Sep 25", "tone": "active"},
            {"role": "Software Engineering Co-op", "organization": "Harbor Tech", "stage": "In review", "updated": "Updated Sep 21", "tone": "review"},
        ],
        "opportunities": [
            {"role": "Data Engineering Intern", "organization": "Meridian Works", "location": "Remote | Internship", "skills": "Python | SQL | dbt"},
            {"role": "Application Developer Co-op", "organization": "Northstar Systems", "location": "Boston | Co-op", "skills": "Java | REST APIs"},
        ],
        "navigation": [
            {"label": "Dashboard", "icon": "\U0001F3E0", "target": "student-dashboard"},
            {"label": "My Profile", "icon": "\U0001F464", "target": "student-profile"},
            {"label": "My Skills", "icon": "\U0001F4CA", "target": "student-skills"},
            {"label": "Projects", "icon": "\U0001F4C1", "target": "student-projects"},
            {"label": "Connected Platforms", "icon": "\U0001F517", "target": "student-platforms"},
            {"label": "Assessments", "icon": "\U0001F4DD", "target": "student-assessments"},
            {"label": "Hackathons", "icon": "\U0001F3C6", "target": "student-hackathons"},
            {"label": "Jobs & Internships", "icon": "\U0001F4BC", "target": "student-opportunities"},
            {"label": "Applications", "icon": "\U0001F4CB", "target": "student-applications"},
            {"label": "Certifications", "icon": "\U0001F4DC", "target": "student-certifications"},
            {"label": "My Progress", "icon": "\U0001F4C8", "target": "student-progress"},
            {"label": "AI Recommendations", "icon": "\U0001F916", "target": "student-recommendations"},
            {"label": "Messages", "icon": "\U0001F4AC", "target": "student-messages"},
            {"label": "Notifications", "icon": "\U0001F514", "target": "student-notifications"},
            {"label": "Settings", "icon": "\u2699", "target": "student-settings"},
        ],
        "platforms": [
            {"name": "GitHub", "detail": "Repository evidence", "state": "Not connected"},
            {"name": "LeetCode", "detail": "Problem-solving profile", "state": "Not connected"},
            {"name": "LinkedIn", "detail": "Professional profile", "state": "Not connected"},
        ],
        "hackathons": [
            {"name": "Campus Climate Challenge", "organizer": "Northbridge Institute", "status": "Submission complete", "date": "Sep 12, 2026"},
            {"name": "Open Source Weekend", "organizer": "Meridian Works", "status": "Registration open", "date": "Oct 18, 2026"},
        ],
        "certifications": [
            {"name": "Cloud Foundations", "issuer": "Northbridge Learning Lab", "status": "Evidence pending", "date": "Aug 2026"},
        ],
        "progress": [
            {"period": "JUN", "count": 1},
            {"period": "JUL", "count": 2},
            {"period": "AUG", "count": 3},
            {"period": "SEP", "count": 4},
        ],
        "notifications": [
            {"title": "Java assessment verified", "detail": "Your profile evidence was updated.", "date": "Sep 14"},
            {"title": "Application moved to assessment", "detail": "Backend Intern / Meridian Works", "date": "Sep 12"},
            {"title": "New role matches your interests", "detail": "Data Engineering Intern", "date": "Sep 10"},
        ],
    },
    "institution": {
        "name": "Northbridge Institute",
        "term": "Fall 2026 cohort",
        "metrics": [
            {"label": "Students", "value": "1,248", "note": "Across 4 departments"},
            {"label": "Discoverable profiles", "value": "764", "note": "Student opt-in"},
            {"label": "Evidence records", "value": "4,830", "note": "Projects and assessments"},
            {"label": "Placements recorded", "value": "112", "note": "Current cohort"},
        ],
        "departments": [
            {"name": "Computer Science", "students": "486 students", "coverage": 74},
            {"name": "Data Science", "students": "302 students", "coverage": 69},
            {"name": "Information Systems", "students": "278 students", "coverage": 53},
            {"name": "Computer Engineering", "students": "182 students", "coverage": 61},
        ],
        "pipeline": [
            {"stage": "Applied", "count": 842, "width": 100},
            {"stage": "Assessment", "count": 412, "width": 72},
            {"stage": "Interview", "count": 207, "width": 49},
            {"stage": "Offer", "count": 133, "width": 36},
            {"stage": "Placed", "count": 112, "width": 31},
        ],
        "activity": [
            {"title": "Java assessment completed", "detail": "96 student submissions", "date": "Sep 24"},
            {"title": "New project evidence added", "detail": "18 profiles updated", "date": "Sep 22"},
            {"title": "Placement status updated", "detail": "7 offers recorded", "date": "Sep 19"},
        ],
    },
}
